AWSTemplateFormatVersion: 2010-09-09
Description: This is to Create a custom VPC in AWS
Parameters:
  VPCIPRange:
     Description: Enter the ip address range based 
     Type: String
     Default: 10.0.0.0/24
Resources: 
 CloudformationVPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: !Ref VPCIPRange
    EnableDnsSupport: 'true'
    EnableDnsHostnames: 'true'
    Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-VPC'
      - Key: stack
        Value: production
Outputs:
  MyVPC:
    Description: this is my VPCID
    Value: !GetAtt
      - CloudformationVPC
      - VpcId
    Export:
      Name: !Sub '${AWS::StackName}-myvpcid'
